apiVersion: v1
kind: Cluster
metadata:
  name: new-cluster
  region: PHX1
spec:
  nodeCount: 1
  size: g4s.kube.medium
  clusterType: k3s
  masterCluster: true
  firewall:
    enabled: true
    rules:
      - protocol: tcp
        startPort: "6443"
        endPort: "6443"
        cidr:
          - "0.0.0.0/0"
        direction: ingress
      - protocol: tcp
        startPort: "80"
        endPort: "80"
        cidr:
          - "0.0.0.0/0"
        direction: ingress
      - protocol: tcp
        startPort: "443"
        endPort: "443"
        cidr:
          - "0.0.0.0/0"
        direction: ingress
  ingress:
    enabled: true
    loadBalancer: true