apiVersion: v1
kind: Cluster
metadata:
    name: test-cluster
    region: PHX1
spec:
    provider: civo
    nodes:
        - g4s.kube.small
    clusterType: k3s
    firewall:
        enabled: true
        rules:
            - protocol: tcp
              startPort: "6443"
              endPort: "6443"
              cidr:
                - 0.0.0.0/0
              direction: ingress
    ingress:
        enabled: true
        loadBalancer: true
